version: "3.9"

services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret

      #comlink
      COMLINK_SECRET_KEY: my-secret-key
      COMLINK_ACCESS_KEY: my-access-key
      COMLINK_URL: http://host.docker.internal:5000
    restart: unless-stopped